### ISSUE TITLE
Implement custom renderers property

### ISSUE THREAD

**Issue by dfguerrerom** [trungleduc/ipecharts#13]
After reading the https://echarts.apache.org/en/api.html#echarts documentation, I found an option to change the renderer of the widget, either 'canvas' or 'svg', which can be very useful.
This feature doesn't seem too complicated to implement, just a couple of lines of code, however, the library now has two types of widgets, meaning that any new feature has to be added to the both of them, what do you think about adding a `BaseWidgetView` and a `BaseWidgetModel`? it would be easier to implement these methods... if you want I could draft a PR and/or follow your indications? if you see it as something feasible?

**Comment by trungleduc** [comment]
> what do you think about adding a BaseWidgetView and a BaseWidgetModel? it would be easier to implement these methods... 

I agree, this should be the way to go! And we should allow passing all options in the  `echarts.init` call from the Python side. Your PRs are very welcome!

**Comment by trungleduc** [comment]
Fixed by #16
