### ISSUE TITLE
charts get squished when scrolling

### ISSUE THREAD

**Issue by dfguerrerom** [trungleduc/ipecharts#17]
Charts get squished after you leave them out your view (by scrolling) and then you create a new widget, which I think that triggers the `resize` event?

[Screencast from 01-10-2024 11:14:29.webm](https://github.com/user-attachments/assets/2d64b5af-0e5d-4b1d-836a-a437c39754eb)

**Comment by trungleduc** [comment]
Hmm, are you using the Windowing mode of JupyterLab https://jupyterlab.readthedocs.io/en/latest/getting_started/changelog.html#full-notebook-windowing-mode-improvements ?

**Comment by trungleduc** [comment]
yeah, it looks related. I will check it tonight

**Comment by trungleduc** [comment]
what is the version of JupyterLab you are using?

**Comment by dfguerrerom** [comment]
I'm using `jupyterlab == 4.2.5` couldn't you reproduce this issue?

**Comment by dfguerrerom** [comment]
but does that also explain why the same happen in Voila?

[Screencast from 01-10-2024 12:10:57.webm](https://github.com/user-attachments/assets/357349c2-e5df-4dd2-a0da-a7d9d4db9748)

**Comment by trungleduc** [comment]
the issue in voila is when you close the accordion ? I might be the same problem of having 0-dimension parent. Fixing this issue will apply to both voila and jupyterlab

**Comment by dfguerrerom** [comment]
the accordion triggers a window resize event, but as the charts are inside an expansion panel, by that moment, they get squished... think that specific one I can fix by triggering a resize window after expanding the panels.

**Comment by trungleduc** [comment]
Fixed by #18
