### ISSUE TITLE
wong labextension version should trigger an error?

### ISSUE THREAD

**Issue by dfguerrerom** [trungleduc/ipecharts#20]
I work on a system where its configuration I briefly explained here https://github.com/voila-dashboards/voila/issues/1494. I have installed `ipecharts==1.0.7" in the system and `ipecharts==1.0.8" in a virtual environment.

If I launch `jupyter lab` (from my system) and I use the kernel where I have installed `ipecharts==1.0.8" I should receive an error saying that 1.0.8 is not registered but 1.0.7 it is.... however, that error doesn't show up...

Might if be because this file https://github.com/trungleduc/ipecharts/blob/main/ipecharts/_frontend.py is not inline?

**Comment by trungleduc** [comment]
Generally, the minimum frontend package version does not need to be in sync 100% with the Python package, we only bump the minimum frontend version on the python side if it breaks completely the compatibility.

**Comment by dfguerrerom** [comment]
got it! I said that because I was testing 1.0.8 and, even though the traits were available in the python side, they didn't trigger any change to the view. Of course, this is something that happens only if you have custom installations as mine. I think I can close this issue here.
