### ISSUE TITLE
Move to `jupyter-widgets-contrib`?

### ISSUE THREAD

**Issue by jtpio** [trungleduc/ipecharts#7]
There is a new `jupyter-widgets-contrib` org: https://github.com/jupyter-widgets-contrib, similar to the one for JupyterLab extensions: https://github.com/jupyterlab-contrib.

Maybe it could be interesting to move the repo there, mostly for visibility?

**Comment by trungleduc** [comment]
Hi @jtpio, I want to keep it under my account for now.

**Comment by jtpio** [comment]
OK no problem.

Would it be possible to link to it from this page otherwise? https://jupyter-widgets-contrib.github.io/extensions.html#libraries-from-elsewhere

**Comment by trungleduc** [comment]
ok, will do
