### ISSUE TITLE
support for events?

### ISSUE THREAD

**Issue by dfguerrerom** [trungleduc/ipecharts#8]
I would like to trigger some events from the user's interaction with the graphs as echarts describes in https://echarts.apache.org/handbook/en/concepts/event, is there any way to do it with this extension?

**Comment by trungleduc** [comment]
Hi, it's possible to add these events to the extension. I can add the same APIs as in the JS side to python. For example

```python
from ipecharts import EChartsWidget
...
my_chart = EChartsWidget(option=option)

def my_callback(params):
     print(params)

my_chart.on('mouseover', { "seriesIndex": 1, "name":  "xx" }, my_callback)
```

I can work on this feature in a few weeks.

**Comment by dfguerrerom** [comment]
Wow, awesome! Thanks I will test it.

**Comment by trungleduc** [comment]
I will add action dispatching later then release 1.1
