### ISSUE TITLE
How to change the default height of the echart widget?

### ISSUE THREAD

**Issue by dfguerrerom** [trungleduc/ipecharts#9]
I need to create a 150px height bar chart, but I saw that even though I can edit the `grid` property, there's a default css class applied to all the widgets with a `500px` height, so the widget container will remain with its default size while the chart will use the given height.

I tried doing `my_chart.add_class('new_height_class')`, but I also noticed that  the `update_classes` method doesn't `resize()` the chart, so I have to change the window size to make this change to happen.
Ideally I would like to achieve two things, pass a `class_` property to the `ECharstWidget()`,  and, trigger a `resize()` event after a new css class has added/removed.

I have already edited the `ECharts`... classes to trigger the resize when the css classes change, but I cannot make the initial state to change... would you mind to review a PR? or giving me any clue?

**Comment by trungleduc** [comment]
widget height is hard-coded here https://github.com/trungleduc/ipecharts/blob/82993e38ac9e2bd29ec235ec2be82b7b91c66cfd/style/base.css#L7

Ideally, EChartsWidget and EChartsRawWidget should have a `style` option where you can pass the your CSS config to the JS part. 
You can refer to the implementation of the `FlexLayout` widget [here](https://github.com/trungleduc/ipyflex/blob/18500c388124206cd8fbef307854f61f3c316b9c/ipyflex/flex_layout.py#L70) and [here](https://github.com/trungleduc/ipyflex/blob/18500c388124206cd8fbef307854f61f3c316b9c/src/widget.tsx#L132) for the JS part

**Comment by trungleduc** [comment]
And PRs are very welcome
